# Generated by Django 2.2.3 on 2019-08-05 18:47

import os
import shutil

from django.core.files import File
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fancy_imagefield
import ckeditor


def initial_slides(apps, schema_editor):
    Carousel = apps.get_model("carousel", "Carousel")
    carousel = Carousel.objects.create(slug='home_header_carousel')
    Slide = apps.get_model("carousel", "Slide")

    if not os.path.exists(settings.MEDIA_ROOT):
        os.mkdirs(settings.MEDIA_ROOT)

    image_media_name = os.path.join(
        settings.MEDIA_ROOT,
        os.path.basename('sample-slide-image.jpg')
    )
    shutil.copy(
        os.path.join(
            os.path.dirname(os.path.dirname(
                __file__
            )),
            'static', 'carousel', 'images', 'sample-slide-image.jpg'
        ),
        image_media_name
    )
    with open(image_media_name, 'rb') as image:
        for i in range(3):
            Slide.objects.create(
                title='The Best Medical Service',
                content=('Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                         'Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. '
                         'Ut ac ligula sapien. Suspendisse cursus faucibus finibus.'),
                details_link=None,
                priority=i + 1,
                image=File(image, name='sample-slide-image.jpg'),
                carousel=carousel
            )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('details_link', models.URLField(blank=True, null=True)),
                ('priority', models.IntegerField()),
                ('carousel', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='carousel.Carousel'
                )),
                ('image', models.ImageField(upload_to='carousels_slides')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['priority'],
            },
        ),
        migrations.RunPython(
            code=initial_slides,
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='created_at',
        ),
        migrations.AddField(
            model_name='carousel',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='slide',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='carousel',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='slides',
                to='carousel.Carousel',
                verbose_name='Carousel'
            ),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='details_link',
            field=models.URLField(blank=True, null=True, verbose_name='Details Link'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='carousels_slides', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='priority',
            field=models.IntegerField(verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=fancy_imagefield.fields.ImageField(
                upload_to='carousels_slides',
                validators=[fancy_imagefield.validators.MaxSizeValidator(1024)],
                verbose_name='Image'
            ),
        ),
    ]
