# Generated by Django 2.2.3 on 2019-07-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.FileField(default=None, upload_to='carousels_slides'),
            preserve_default=False,
        ),
    ]
