# Generated by Django 2.2.3 on 2019-07-21 18:14

import os
import shutil

from django.core.files import File
from django.conf import settings
from django.db import migrations


def initial_slides(apps, schema_editor):
    Carousel = apps.get_model("carousel", "Carousel")
    carousel = Carousel.objects.create(slug='home_header_carousel')
    Slide = apps.get_model("carousel", "Slide")

    if not os.path.exists(settings.MEDIA_ROOT):
        os.mkdirs(settings.MEDIA_ROOT)

    image_media_name = os.path.join(
        settings.MEDIA_ROOT,
        os.path.basename('sample-slide-image.jpg')
    )
    shutil.copy(
        os.path.join(
            os.path.dirname(os.path.dirname(
                __file__
            )),
            'static', 'carousel', 'images', 'sample-slide-image.jpg'
        ),
        image_media_name
    )
    with open(image_media_name, 'rb') as image:
        for i in range(3):
            Slide.objects.create(
                title='The Best Medical Service',
                content=('Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                         'Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. '
                         'Ut ac ligula sapien. Suspendisse cursus faucibus finibus.'),
                details_link=None,
                priority=i + 1,
                image=File(image, name='sample-slide-image.jpg'),
                carousel=carousel
            )


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_auto_20190720_1547'),
    ]

    operations = [
        migrations.RunPython(initial_slides)
    ]
