# Generated by Django 2.2.3 on 2019-07-25 16:50

import os
import shutil

from django.core.files import File
from django.conf import settings
from django.db import migrations


def initial_services_page(apps, schema_editor):
    Article = apps.get_model("services", "Article")
    DescriptionTab = apps.get_model("services", "DescriptionTab")
    db_alias = schema_editor.connection.alias

    Article.objects.using(db_alias).create(
        title='Only Top Quality Services',
        description=(
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
            'Donec malesuada lorem ma ximus mauris scelerisque, at rutrum nulla dictum. '
            'Ut ac ligula sapien. Suspendisse cursus faucibus finibus. Curabitur ut '
            'augue finibus, luctus tortor at, ornare erat. Nulla facilisi. Sed est risus, '
            'laoreet et quam non, malesuada viverra accumsan leo.'
        )
    )

    if not os.path.exists(settings.MEDIA_ROOT):
        os.mkdirs(settings.MEDIA_ROOT)

    tab_image = os.path.join(
        os.path.dirname(os.path.dirname(__file__)),
        'static',
        'services',
        'images',
        'service-tab-img.png'
    )
    tab_image_name = os.path.join(
        settings.MEDIA_ROOT, 'service-tab-img.png'
    )
    shutil.copy(tab_image, tab_image_name)

    tab_names = [
        'Pellentesque pulvinar', 'Pellentesque lacinia',
        'Consectetur diam', 'CMauris tortor', 'Phasellus sit amet'
    ]
    for name in tab_names:
        with open(tab_image_name, 'rb') as image:
            DescriptionTab.objects.using(db_alias).create(
                name=name,
                title='Scelerisque, at rutrum nulla dictum. Ut ac ligula sapien.',
                description=(
                    'Amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris '
                    'scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse '
                    'cursus faucibus finibus. Curabitur ut augue finibus, luctus tortor at, '
                    'ornare erat. Nulla facilisi. Sed est risus, laoreet et quam non, viverra '
                    'accumsan leo. Amet, consectetur adipiscing elit. Donec malesuada lorem '
                    'maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. '
                    'Suspendisse cursus faucibus finibus'
                ),
                image=File(image, name=os.path.basename(tab_image_name))
            )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_services_page)
    ]
