# Generated by Django 2.2.3 on 2019-08-05 18:53
import os
import shutil

from django.core.files import File
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import fancy_imagefield.fields
import fancy_imagefield.validators


def initial_departments(apps, schema_editor):
    Department = apps.get_model("departmentsbox", "Department")
    db_alias = schema_editor.connection.alias
    info = [
        {
            'title': 'Cardioology',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'cardiogram.png'
            )
        },
        {
            'title': 'Gastroenterology',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'stomach.png'
            )
        },
        {
            'title': 'Medical Lab',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'blood.png'
            )
        },
        {
            'title': 'Dental Care',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'teeth.png'
            )
        },
        {
            'title': 'Surgery',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'stretcher.png'
            )
        },
        {
            'title': 'Neurology',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'scanner.png'
            )
        },
        {
            'title': 'Orthopaedy',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'bones.png'
            )
        },
        {
            'title': 'Pediatry',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'blood-donation.png'
            )
        },
        {
            'title': 'Ophthalmology',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'glasses.png'
            )
        },
    ]
    if not os.path.exists(settings.MEDIA_ROOT):
        os.mkdirs(settings.MEDIA_ROOT)
    for department_info in info:
        logo_media_name = os.path.join(
            settings.MEDIA_ROOT,
            os.path.basename(department_info['logo'])
        )
        shutil.copy(
            department_info['logo'],
            logo_media_name
        )
        with open(logo_media_name, 'rb') as logo:
            Department.objects.using(db_alias).create(
                title=department_info['title'],
                descriptions=department_info['descriptions'],
                logo=File(logo, name=os.path.basename(department_info['logo']))
            )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='department_logos')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.RunPython(
            code=initial_departments,
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.AddField(
            model_name='department',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='department',
            name='descriptions',
            field=models.CharField(max_length=250, verbose_name='Descriptions'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.ImageField(upload_to='department_logos', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=fancy_imagefield.fields.ImageField(
                upload_to='department_logos',
                validators=[fancy_imagefield.validators.MaxSizeValidator(256)],
                verbose_name='Logo'
            ),
        ),
    ]
