# Generated by Django 2.2.3 on 2019-09-06 11:28

from django.db import migrations, models
import django.db.models.deletion

old_departments = []


def delete_old_departments(apps, schema_editor):
    Department = apps.get_model("departmentsbox", "Department")
    db_alias = schema_editor.connection.alias

    for dep in Department.objects.using(db_alias).all():
        old_departments.append(dep)
        dep.delete()


def update_old_departments(apps, schema_editor):
    Department = apps.get_model("departmentsbox", "Department")
    DepartmentGroup = apps.get_model("departmentsbox", "DepartmentGroup")
    # db_alias = schema_editor.connection.alias

    home_group = DepartmentGroup.objects.create(
        slug='home_departments', title="Our Departments"
    )
    services_group = DepartmentGroup.objects.create(
        slug='services_departments', title="Our Departments"
    )

    for dep in old_departments:
        department = Department()
        for field in dep._meta.fields:
            setattr(department, field.name, getattr(dep, field.name))

        department.group = home_group
        department.save()

        department.id = None
        department.group = services_group
        department.save()


class Migration(migrations.Migration):

    dependencies = [
        ('departmentsbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentGroup',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                )),
                ('slug', models.SlugField(verbose_name='Slug', unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Department Group',
                'verbose_name_plural': 'Department Groups',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.RunPython(
            code=delete_old_departments
        ),
        migrations.AddField(
            model_name='department',
            name='group',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, related_name='children',
                to='departmentsbox.DepartmentGroup', verbose_name='Group'
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=update_old_departments
        ),
    ]
