# Generated by Django 2.2.3 on 2019-07-20 11:18

import os
import shutil

from django.core.files import File
from django.conf import settings
from django.db import migrations


def initial_departments(apps, schema_editor):
    Department = apps.get_model("departmentsbox", "Department")
    db_alias = schema_editor.connection.alias
    info = [
        {
            'title': 'Cardioology',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'cardiogram.png'
            )
        },
        {
            'title': 'Gastroenterology',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'stomach.png'
            )
        },
        {
            'title': 'Medical Lab',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'blood.png'
            )
        },
        {
            'title': 'Dental Care',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'teeth.png'
            )
        },
        {
            'title': 'Surgery',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'stretcher.png'
            )
        },
        {
            'title': 'Neurology',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'scanner.png'
            )
        },
        {
            'title': 'Orthopaedy',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'bones.png'
            )
        },
        {
            'title': 'Pediatry',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'blood-donation.png'
            )
        },
        {
            'title': 'Ophthalmology',
            'descriptions': (
                'Lorem ipsum dolor sit amet, consectetur'
                ' adipiscing elit. Donec malesuada lorem maximus mauris.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'departmentsbox',
                'images',
                'glasses.png'
            )
        },
    ]
    if not os.path.exists(settings.MEDIA_ROOT):
        os.mkdirs(settings.MEDIA_ROOT)
    for department_info in info:
        logo_media_name = os.path.join(
            settings.MEDIA_ROOT,
            os.path.basename(department_info['logo'])
        )
        shutil.copy(
            department_info['logo'],
            logo_media_name
        )
        with open(logo_media_name, 'rb') as logo:
            Department.objects.using(db_alias).create(
                title=department_info['title'],
                descriptions=department_info['descriptions'],
                logo=File(logo, name=os.path.basename(department_info['logo']))
            )


class Migration(migrations.Migration):

    dependencies = [
        ('departmentsbox', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_departments)
    ]
