# Generated by Django 2.2.3 on 2019-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='details_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
