# Generated by Django 2.2.3 on 2019-09-06 11:28

from django.db import migrations
import fancy_imagefield.fields
import fancy_imagefield.validators


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=fancy_imagefield.fields.ImageField(upload_to='', validators=[fancy_imagefield.validators.MaxSizeValidator(1048576)], verbose_name='Image'),
        ),
    ]
