# Generated by Django 2.2.3 on 2019-07-25 03:44

import os
import shutil

from django.core.files import File
from django.conf import settings
from django.db import migrations


def make_about_us_page_defaults(apps, schema_editor):
    History = apps.get_model("about_us", "History")
    Faq = apps.get_model("about_us", "Faq")
    Stuff = apps.get_model("about_us", "Stuff")
    ClinicTeamMember = apps.get_model("about_us", "ClinicTeamMember")
    db_alias = schema_editor.connection.alias

    if not os.path.exists(settings.MEDIA_ROOT):
        os.mkdirs(settings.MEDIA_ROOT)

    # Initial History
    history_image = os.path.join(
        os.path.dirname(os.path.dirname(__file__)),
        'static',
        'about_us',
        'images',
        'about-history.jpg'
    )
    history_image_name = os.path.join(
        settings.MEDIA_ROOT, 'about-history.jpg'
    )
    shutil.copy(history_image, history_image_name)
    with open(history_image_name, 'rb') as image:
        History.objects.using(db_alias).create(
            title="MedArt History",
            text=(
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
                "Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. "
                "Ut ac ligula sapien. Suspendisse cursus faucibus finibus. "
                "Curabitur ut augue finibus, luctus tortor at, ornare erat. Nulla facilisi. "
                "Sed est risus, laoreet et quam non, viverra accumsan leo. "
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
                "Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. "
                "Ut ac ligula sapien. Suspendisse cursus faucibus finibus. "
                "Curabitur ut augue finibus, luctus tortor at, ornare erat."
            ),
            image=File(image, name=os.path.basename(history_image_name))
        )

    # Initial Faq
    faqs_info = [
        {
            'question': 'Elit mir congue ligula et efficitur pellentesqu',
            'answer': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris. Lorem ipsum dolor sit amet, '
                'consectetur adipiscing elit. Donec malesuada lorem maximus mauris.'
            )
        },
        {
            'question': 'Pulvinar elit mi. Integer congue ligula et efficitur',
            'answer': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris. Lorem ipsum dolor sit amet, '
                'consectetur adipiscing elit. Donec malesuada lorem maximus mauris.'
            )
        },
        {
            'question': 'Pellentesque pulvinar elit mi. Integer congue',
            'answer': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris. Lorem ipsum dolor sit amet, '
                'consectetur adipiscing elit. Donec malesuada lorem maximus mauris.'
            )
        }
    ]
    for faq_info in faqs_info:
        Faq.objects.using(db_alias).create(
            **faq_info
        )

    # Initial Stuff
    stuffs_info = [
        {
            'title': 'Professional',
            'description': (
                'Lorem ipsum dolor sit amet, cons ectetur adipiscing elit. Donec males uada lorem.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'about_us',
                'images',
                'stuff-1.png'
            )
        },
        {
            'title': 'Quality',
            'description': (
                'Lorem ipsum dolor sit amet, cons ectetur adipiscing elit. Donec males uada lorem.'
            ),
            'logo': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'about_us',
                'images',
                'stuff-2.png'
            )
        }
    ]
    for stuf_info in stuffs_info:
        logo_name = os.path.join(
            settings.MEDIA_ROOT, os.path.basename(stuf_info['logo'])
        )
        shutil.copy(stuf_info['logo'], logo_name)

        with open(logo_name, 'rb') as logo:
            Stuff.objects.using(db_alias).create(
                title=stuf_info['title'],
                description=stuf_info['description'],
                logo=File(logo, name=os.path.basename(stuf_info['logo']))
            )

    # Initial Medical Team
    team_info = [
        {
            'name': 'Christinne Smith',
            'degree': 'PHD Surgeon',
            'avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'about_us',
                'images',
                'team-1.jpg'
            )
        },
        {
            'name': 'Anna Gustav',
            'degree': 'PHD Surgeon',
            'avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'about_us',
                'images',
                'team-2.jpg'
            )
        },
        {
            'name': 'Phillip Williams',
            'degree': 'PHD Surgeon',
            'avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'about_us',
                'images',
                'team-3.jpg'
            )
        },
        {
            'name': 'Gina James',
            'degree': 'PHD Surgeon',
            'avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'about_us',
                'images',
                'team-4.jpg'
            )
        }
    ]

    for member in team_info:
        avatar_name = os.path.join(
            settings.MEDIA_ROOT, os.path.basename(member['avatar'])
        )
        shutil.copy(member['avatar'], avatar_name)

        with open(avatar_name, 'rb') as avatar:
            ClinicTeamMember.objects.using(db_alias).create(
                name=member['name'],
                degree=member['degree'],
                avatar=File(avatar, name=os.path.basename(member['avatar']))
            )


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_history_details_link'),
    ]

    operations = [
        migrations.RunPython(make_about_us_page_defaults)
    ]
