# Generated by Django 2.2.3 on 2019-08-05 19:00
import os
import shutil

from django.core.files import File
from django.conf import settings
import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import fancy_imagefield.fields
import fancy_imagefield.validators


def initial_testimonials(apps, schema_editor):
    Testimonial = apps.get_model("testimonials", "Testimonial")
    db_alias = schema_editor.connection.alias
    info = [
        {
            'user_full_name': 'Russell Stephens',
            'location': 'University in UK',
            'text': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris scelerisque, at rutrum '
                'nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus '
                'finibus. Curabitur ut augue finibus, luctus tortor at, ornare '
                'erat. Nulla facilisi. Sed est risus, laoreet et quam non, viverra '
                'accumsan leo.'
            ),
            'user_avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'testimonials',
                'images',
                'user-1.jpg'
            )
        },
        {
            'user_full_name': 'Roger Kohen',
            'location': 'Gagool Co',
            'text': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris scelerisque, at rutrum '
                'nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus '
                'finibus. Curabitur ut augue finibus, luctus tortor at, ornare '
                'erat. Nulla facilisi. Sed est risus, laoreet et quam non, viverra '
                'accumsan leo.'
            ),
            'user_avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'testimonials',
                'images',
                'user-2.jpg'
            )
        },
        {
            'user_full_name': 'James Mccarty',
            'location': 'Big Picture Inc',
            'text': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris scelerisque, at rutrum '
                'nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus '
                'finibus. Curabitur ut augue finibus, luctus tortor at, ornare '
                'erat. Nulla facilisi. Sed est risus, laoreet et quam non, viverra '
                'accumsan leo.'
            ),
            'user_avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'testimonials',
                'images',
                'user-3.jpg'
            )
        },
        {
            'user_full_name': 'Andy Cage',
            'location': 'Galaxy Zone co',
            'text': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris scelerisque, at rutrum '
                'nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus '
                'finibus. Curabitur ut augue finibus, luctus tortor at, ornare '
                'erat. Nulla facilisi. Sed est risus, laoreet et quam non, viverra '
                'accumsan leo.'
            ),
            'user_avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'testimonials',
                'images',
                'user-4.jpg'
            )
        }
    ]
    if not os.path.exists(settings.MEDIA_ROOT):
        os.makedirs(settings.MEDIA_ROOT)
    for testimonial_info in info:
        avatar_media_name = os.path.join(
            settings.MEDIA_ROOT,
            os.path.basename(testimonial_info['user_avatar'])
        )
        shutil.copy(
            testimonial_info['user_avatar'],
            avatar_media_name
        )
        with open(avatar_media_name, 'rb') as avatar:
            Testimonial.objects.using(db_alias).create(
                user_full_name=testimonial_info['user_full_name'],
                location=testimonial_info['location'],
                text=testimonial_info['text'],
                user_avatar=File(avatar, name=os.path.basename(testimonial_info['user_avatar']))
            )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_full_name', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('user_avatar', models.ImageField(default='', upload_to='testimonial_avatars')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.RunPython(
            code=initial_testimonials,
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user_avatar',
            field=models.ImageField(upload_to='testimonial_avatars', verbose_name='User Avatar'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user_full_name',
            field=models.CharField(max_length=140, verbose_name='User Full Name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user_avatar',
            field=fancy_imagefield.fields.ImageField(
                upload_to='testimonial_avatars',
                validators=[fancy_imagefield.validators.MaxSizeValidator(512)],
                verbose_name='User Avatar'
            ),
        ),
    ]
