# Generated by Django 2.2.3 on 2019-07-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='user_avatar',
            field=models.ImageField(default='', upload_to='testimonial_avatars'),
            preserve_default=False,
        ),
    ]
