# Generated by Django 2.2.3 on 2019-07-20 15:55

# Generated by Django 2.2.3 on 2019-07-20 15:41

import os
import shutil

from django.core.files import File
from django.conf import settings
from django.db import migrations


def initial_testimonials(apps, schema_editor):
    Testimonial = apps.get_model("testimonials", "Testimonial")
    db_alias = schema_editor.connection.alias
    info = [
        {
            'user_full_name': 'Russell Stephens',
            'location': 'University in UK',
            'text': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris scelerisque, at rutrum '
                'nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus '
                'finibus. Curabitur ut augue finibus, luctus tortor at, ornare '
                'erat. Nulla facilisi. Sed est risus, laoreet et quam non, viverra '
                'accumsan leo.'
            ),
            'user_avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'testimonials',
                'images',
                'user-1.jpg'
            )
        },
        {
            'user_full_name': 'Roger Kohen',
            'location': 'Gagool Co',
            'text': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris scelerisque, at rutrum '
                'nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus '
                'finibus. Curabitur ut augue finibus, luctus tortor at, ornare '
                'erat. Nulla facilisi. Sed est risus, laoreet et quam non, viverra '
                'accumsan leo.'
            ),
            'user_avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'testimonials',
                'images',
                'user-2.jpg'
            )
        },
        {
            'user_full_name': 'James Mccarty',
            'location': 'Big Picture Inc',
            'text': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris scelerisque, at rutrum '
                'nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus '
                'finibus. Curabitur ut augue finibus, luctus tortor at, ornare '
                'erat. Nulla facilisi. Sed est risus, laoreet et quam non, viverra '
                'accumsan leo.'
            ),
            'user_avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'testimonials',
                'images',
                'user-3.jpg'
            )
        },
        {
            'user_full_name': 'Andy Cage',
            'location': 'Galaxy Zone co',
            'text': (
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Donec malesuada lorem maximus mauris scelerisque, at rutrum '
                'nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus '
                'finibus. Curabitur ut augue finibus, luctus tortor at, ornare '
                'erat. Nulla facilisi. Sed est risus, laoreet et quam non, viverra '
                'accumsan leo.'
            ),
            'user_avatar': os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'static',
                'testimonials',
                'images',
                'user-4.jpg'
            )
        }
    ]
    if not os.path.exists(settings.MEDIA_ROOT):
        os.mkdirs(settings.MEDIA_ROOT)
    for testimonial_info in info:
        avatar_media_name = os.path.join(
            settings.MEDIA_ROOT,
            os.path.basename(testimonial_info['user_avatar'])
        )
        shutil.copy(
            testimonial_info['user_avatar'],
            avatar_media_name
        )
        with open(avatar_media_name, 'rb') as avatar:
            Testimonial.objects.using(db_alias).create(
                user_full_name=testimonial_info['user_full_name'],
                location=testimonial_info['location'],
                text=testimonial_info['text'],
                user_avatar=File(avatar, name=os.path.basename(testimonial_info['user_avatar']))
            )


class Migration(migrations.Migration):
    dependencies = [
        ('testimonials', '0002_testimonial_user_avatar'),
    ]

    operations = [
        migrations.RunPython(initial_testimonials)
    ]
